# 1. Stack two arrays vertically

Use the array given below:

array1 = np.arange(10).reshape(2,-1)

array2 = np.repeat(1, 10).reshape(2,-1)

In [6]:
import numpy as np
array1 = np.arange(10).reshape(2,-1)
# print(array1)
array2 = np.repeat(1, 10).reshape(2,-1)
# print(array2)
ans=np.vstack((array1,array2))
print(ans)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
